### ISSUE TITLE
Error while installing home-manager on fresh deck

### ISSUE THREAD

**Issue by redoxeon** [quag/user-nix-steam-deck#1]
I'm not sure what I've done wrong here. Are there any prereqs that I need to have set up first? I had it working, but I reset my steam deck for some other stuff and while trying to run this on the fresh deck, I'm getting this error at the end.

```
Installing home-manager
setting flag on 'nix-2.11.1'
building '/nix/store/0v5mff0yqpgciamphv2nqiff5gpiqvjn-user-environment.drv'...
path '/home/deck/nix/home/.config/nixpkgs/flake.nix' does not contain a 'flake.nix', searching up
warning: creating lock file '/home/deck/nix/home/.config/nixpkgs/flake.lock'
error: 'nixFlakes' has been renamed to/replaced by 'nixVersions.stable'
(use '--show-trace' to show detailed location information)
user-nix-steam-deck/user-nix-steam-deck.sh: 
user-nix-steam-deck/user-nix-steam-deck.sh: home-manager-flake.install failed

```

**Comment by quag** [comment]
Thank you for reporting the problem! I have pushed a new install script that should fix the problem. Can you confirm that the latest install script works?

The error is because the nixFlakes package is no longer available (or needed) as the standard nix tool now has flakes. I have switched from installing the nixFlakes package to installing the standard nix package.

**Comment by redoxeon** [comment]
Works perfectly! Thanks for having that figured out so fast. I'm brand new to nix so I'm still learning how to do it all.
